name: portainer
version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "${HTTP_PORT}:8000"
      - "${HTTPS_PORT}:9443"
      - "9000:9000"
        #    command: >
        #      --sslcert /certs/live/${DOMAIN}/fullchain.pem
        #      --sslkey /certs/live/${DOMAIN}/privkey.pem
    volumes:
      #      - ${CERT_PATH}/${DOMAIN}:/certs/live/${DOMAIN}:ro
      #      - ${ARCHIVE_PATH}/${DOMAIN}:/certs/archive/${DOMAIN}:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}:/data
    networks:
      - default
      - traefik-network

networks:
  traefik-network:
    external: true
    name: traefik-network
